"""empty message

Revision ID: 1637e7e47600
Revises: f3d9c76b0fa9
Create Date: 2022-07-28 11:42:04.363605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1637e7e47600'
down_revision = 'f3d9c76b0fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_book_suggestions_book_author_key', 'user_book_suggestions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_book_suggestions_book_author_key', 'user_book_suggestions', ['book_author'])
    # ### end Alembic commands ###
